// [303] This file should not require any modifications for assignment #1

#pragma once

#include <cstring>
#include <iostream>

/**
 * Print an error message that combines some application-specific text with the
 * standard unix error message that accompanies errno.
 *
 * @param err    The error code that was generated by the program
 * @param prefix The text to display before the error message
 */
void sys_error(std::size_t err, const char *prefix) {
  char buf[1024];
  std::cerr << prefix << " " << strerror_r(err, buf, sizeof(buf)) << std::endl;
}